//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EarTrumpet.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EarTrumpet.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About {Name} add-on.
        /// </summary>
        public static string AboutThisAddonText {
            get {
                return ResourceManager.GetString("AboutThisAddonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string AddonNameText {
            get {
                return ResourceManager.GetString("AddonNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Windows Settings.
        /// </summary>
        public static string AddonUninstallButtonText {
            get {
                return ResourceManager.GetString("AddonUninstallButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This add-on can be removed using the Windows Settings app..
        /// </summary>
        public static string AddonUninstallDescriptionText {
            get {
                return ResourceManager.GetString("AddonUninstallDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall.
        /// </summary>
        public static string AddonUninstallTitle {
            get {
                return ResourceManager.GetString("AddonUninstallTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{Volume}% volume - {Name}&quot;.
        /// </summary>
        public static string AppOrDeviceFormatAccessibleText {
            get {
                return ResourceManager.GetString("AppOrDeviceFormatAccessibleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Muted - {Name}&quot;.
        /// </summary>
        public static string AppOrDeviceMutedFormatAccessibleText {
            get {
                return ResourceManager.GetString("AppOrDeviceMutedFormatAccessibleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apps.
        /// </summary>
        public static string AppsListAccessibleText {
            get {
                return ResourceManager.GetString("AppsListAccessibleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CloseButtonAccessibleText {
            get {
                return ResourceManager.GetString("CloseButtonAccessibleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CloseButtonText {
            get {
                return ResourceManager.GetString("CloseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse to show only the default playback device.
        /// </summary>
        public static string CollapseAccessibleText {
            get {
                return ResourceManager.GetString("CollapseAccessibleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string ContextMenuExitTitle {
            get {
                return ResourceManager.GetString("ContextMenuExitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No playback devices found.
        /// </summary>
        public static string ContextMenuNoDevices {
            get {
                return ResourceManager.GetString("ContextMenuNoDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send feedback.
        /// </summary>
        public static string ContextMenuSendFeedback {
            get {
                return ResourceManager.GetString("ContextMenuSendFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EarTrumpet couldn&apos;t start.
        /// </summary>
        public static string CriticalFailureDialogHeaderText {
            get {
                return ResourceManager.GetString("CriticalFailureDialogHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A broken font on your system is preventing EarTrumpet from starting.
        ///
        ///Open [https://eartrumpet.app/jmp/fixfonts] now?.
        /// </summary>
        public static string CriticalFailureFontLookupHelpText {
            get {
                return ResourceManager.GetString("CriticalFailureFontLookupHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always use the default playback device.
        /// </summary>
        public static string DefaultDeviceText {
            get {
                return ResourceManager.GetString("DefaultDeviceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default shortcut.
        /// </summary>
        public static string DefaultHotkeyDescriptionText {
            get {
                return ResourceManager.GetString("DefaultHotkeyDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management.
        /// </summary>
        public static string DefaultManagementGroupName {
            get {
                return ResourceManager.GetString("DefaultManagementGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand to show all playback devices.
        /// </summary>
        public static string ExpandAccessibleText {
            get {
                return ResourceManager.GetString("ExpandAccessibleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find a setting.
        /// </summary>
        public static string FindASettingText {
            get {
                return ResourceManager.GetString("FindASettingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume Mixer.
        /// </summary>
        public static string FullWindowTitleText {
            get {
                return ResourceManager.GetString("FullWindowTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string HomeButtonText {
            get {
                return ResourceManager.GetString("HomeButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your shortcut.
        /// </summary>
        public static string HotkeyDescriptionText {
            get {
                return ResourceManager.GetString("HotkeyDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legacy settings.
        /// </summary>
        public static string LegacySettingsPageText {
            get {
                return ResourceManager.GetString("LegacySettingsPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume Mixer.
        /// </summary>
        public static string LegacyVolumeMixerText {
            get {
                return ResourceManager.GetString("LegacyVolumeMixerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More commands.
        /// </summary>
        public static string MoreCommandsAccessibleText {
            get {
                return ResourceManager.GetString("MoreCommandsAccessibleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign this app to a playback device.
        /// </summary>
        public static string MoveButtonAccessibleText {
            get {
                return ResourceManager.GetString("MoveButtonAccessibleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muted.
        /// </summary>
        public static string MutedText {
            get {
                return ResourceManager.GetString("MutedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It doesn&apos;t look like you have any playback devices..
        /// </summary>
        public static string NoDevicesPanelContent {
            get {
                return ResourceManager.GetString("NoDevicesPanelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EarTrumpet: No playback devices.
        /// </summary>
        public static string NoDeviceTrayText {
            get {
                return ResourceManager.GetString("NoDeviceTrayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound settings.
        /// </summary>
        public static string OpenSoundSettingsText {
            get {
                return ResourceManager.GetString("OpenSoundSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playback devices.
        /// </summary>
        public static string PlaybackDevicesText {
            get {
                return ResourceManager.GetString("PlaybackDevicesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send crash data to the EarTrumpet team.
        /// </summary>
        public static string PrivacyCheckboxText {
            get {
                return ResourceManager.GetString("PrivacyCheckboxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy policy.
        /// </summary>
        public static string PrivacyPolicyText {
            get {
                return ResourceManager.GetString("PrivacyPolicyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coming soon.
        /// </summary>
        public static string ProjectADescription {
            get {
                return ResourceManager.GetString("ProjectADescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coming soon.
        /// </summary>
        public static string ProjectATitle {
            get {
                return ResourceManager.GetString("ProjectATitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher:.
        /// </summary>
        public static string PublisherText {
            get {
                return ResourceManager.GetString("PublisherText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording devices.
        /// </summary>
        public static string RecordingDevicesText {
            get {
                return ResourceManager.GetString("RecordingDevicesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results.
        /// </summary>
        public static string SearchBoxNoResultsText {
            get {
                return ResourceManager.GetString("SearchBoxNoResultsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App volume modifier.
        /// </summary>
        public static string SettingsAppVolumeShiftText {
            get {
                return ResourceManager.GetString("SettingsAppVolumeShiftText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hover mouse over a window and scroll up or down while holding the shortcut.
        /// </summary>
        public static string SettingsAppVolumeShiftToolTip {
            get {
                return ResourceManager.GetString("SettingsAppVolumeShiftToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string SettingsCategoryTitle {
            get {
                return ResourceManager.GetString("SettingsCategoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure shortcuts and get help.
        /// </summary>
        public static string SettingsDescriptionText {
            get {
                return ResourceManager.GetString("SettingsDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlimited app volume.
        /// </summary>
        public static string SettingsEnableUnlimitedAppControlText {
            get {
                return ResourceManager.GetString("SettingsEnableUnlimitedAppControlText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows the volume of the app under the mouse to be increased above 100% (When the app reaches 100%, the other apps begin to decrease in volume as the device volume increases to compensate).
        /// </summary>
        public static string SettingsEnableUnlimitedAppControlToolTip {
            get {
                return ResourceManager.GetString("SettingsEnableUnlimitedAppControlToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mute app volume.
        /// </summary>
        public static string SettingsMuteAppVolumeText {
            get {
                return ResourceManager.GetString("SettingsMuteAppVolumeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The app that the mouse is above.
        /// </summary>
        public static string SettingsMuteAppVolumeToolTip {
            get {
                return ResourceManager.GetString("SettingsMuteAppVolumeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mute volume.
        /// </summary>
        public static string SettingsMuteVolumeText {
            get {
                return ResourceManager.GetString("SettingsMuteVolumeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mutes the volume of the current device.
        /// </summary>
        public static string SettingsMuteVolumeToolTip {
            get {
                return ResourceManager.GetString("SettingsMuteVolumeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taskbar flyout.
        /// </summary>
        public static string SettingsOpenEarTrumpetText {
            get {
                return ResourceManager.GetString("SettingsOpenEarTrumpetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens the Taskbar flyout.
        /// </summary>
        public static string SettingsOpenEarTrumpetToolTip {
            get {
                return ResourceManager.GetString("SettingsOpenEarTrumpetToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mixer.
        /// </summary>
        public static string SettingsOpenMixerText {
            get {
                return ResourceManager.GetString("SettingsOpenMixerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens the EarTrumpet Mixer.
        /// </summary>
        public static string SettingsOpenMixerToolTip {
            get {
                return ResourceManager.GetString("SettingsOpenMixerToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsOpenSettingsText {
            get {
                return ResourceManager.GetString("SettingsOpenSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens the EarTrumpet settings page.
        /// </summary>
        public static string SettingsOpenSettingsToolTip {
            get {
                return ResourceManager.GetString("SettingsOpenSettingsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply saved volume preferences.
        /// </summary>
        public static string SettingsOpenVolumesText {
            get {
                return ResourceManager.GetString("SettingsOpenVolumesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applies the saved volume preferences if any exist.
        /// </summary>
        public static string SettingsOpenVolumesToolTip {
            get {
                return ResourceManager.GetString("SettingsOpenVolumesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save volume preferences.
        /// </summary>
        public static string SettingsSaveVolumesText {
            get {
                return ResourceManager.GetString("SettingsSaveVolumesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saves all the volumes in the EarTrumpet default flyout view.
        /// </summary>
        public static string SettingsSaveVolumesToolTip {
            get {
                return ResourceManager.GetString("SettingsSaveVolumesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EarTrumpet Settings.
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use legacy EarTrumpet icon.
        /// </summary>
        public static string SettingsUseLegacyEarTrumpetIcon {
            get {
                return ResourceManager.GetString("SettingsUseLegacyEarTrumpetIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume modifier.
        /// </summary>
        public static string SettingsVolumeShiftText {
            get {
                return ResourceManager.GetString("SettingsVolumeShiftText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scroll up or down while holding shortcut.
        /// </summary>
        public static string SettingsVolumeShiftToolTip {
            get {
                return ResourceManager.GetString("SettingsVolumeShiftToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsWindowText {
            get {
                return ResourceManager.GetString("SettingsWindowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcuts.
        /// </summary>
        public static string ShortcutsPageText {
            get {
                return ResourceManager.GetString("ShortcutsPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sounds.
        /// </summary>
        public static string SoundsControlPanelText {
            get {
                return ResourceManager.GetString("SoundsControlPanelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle mute.
        /// </summary>
        public static string ToggleMuteToolTip {
            get {
                return ResourceManager.GetString("ToggleMuteToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string ToggleSwitchOffText {
            get {
                return ResourceManager.GetString("ToggleSwitchOffText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string ToggleSwitchOnText {
            get {
                return ResourceManager.GetString("ToggleSwitchOnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collect troubleshooting data.
        /// </summary>
        public static string TroubleshootEarTrumpetText {
            get {
                return ResourceManager.GetString("TroubleshootEarTrumpetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        public static string VersionText {
            get {
                return ResourceManager.GetString("VersionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more.
        /// </summary>
        public static string WebsiteText {
            get {
                return ResourceManager.GetString("WebsiteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to EarTrumpet.
        /// </summary>
        public static string WelcomeDialogHeaderText {
            get {
                return ResourceManager.GetString("WelcomeDialogHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Legacy.
        /// </summary>
        public static string WindowsLegacyMenuText {
            get {
                return ResourceManager.GetString("WindowsLegacyMenuText", resourceCulture);
            }
        }
    }
}
